// REDUX ACTION TYPES
export const GETUSERSBYPAGE_REQUEST = 'USERS_GETUSERSBYPAGE_REQUEST';
export const GETUSERSBYPAGE_SUCCESS = 'USERS_GETUSERSBYPAGE_SUCCESS';
export const GETUSERSBYPAGE_FAILURE = 'USERS_GETUSERSBYPAGE_FAILURE';

export const GETUSERBYID_REQUEST = 'USERS_GETUSERBYID_REQUEST';
export const GETUSERBYID_SUCCESS = 'USERS_GETUSERBYID_SUCCESS';
export const GETUSERBYID_FAILURE = 'USERS_GETUSERBYID_FAILURE';

export const DELETEUSER_REQUEST = 'USERS_DELETEUSERREQUEST';
export const DELETEUSER_SUCCESS = 'USERS_DELETEUSERSUCCESS';
export const DELETEUSER_FAILURE = 'USERS_DELETEUSERFAILURE';

export const EDITUSER_REQUEST = 'USERS_EDITUSERREQUEST';
export const EDITUSER_SUCCESS = 'USERS_EDITUSERSUCCESS';
export const EDITUSER_FAILURE = 'USERS_EDITUSERFAILURE';
