// REDUX ACTION TYPES
export const GETUSERSBYPAGE_REQUEST = 'USERS_GETUSERSBYPAGE_REQUEST';
export const GETUSERSBYPAGE_SUCCESS = 'USERS_GETUSERSBYPAGE_SUCCESS';
export const GETUSERSBYPAGE_FAILURE = 'USERS_GETUSERSBYPAGE_FAILURE';
