// REDUX ACTION TYPES
export const GETUSERSBYPAGE_REQUEST = 'USERS_GETUSERSBYPAGE_REQUEST';
export const GETUSERSBYPAGE_SUCCESS = 'USERS_GETUSERSBYPAGE_SUCCESS';
export const GETUSERSBYPAGE_FAILURE = 'USERS_GETUSERSBYPAGE_FAILURE';

export const DELETEUSER_REQUEST = 'USERS_DELETEUSERREQUEST';
export const DELETEUSER_SUCCESS = 'USERS_DELETEUSERSUCCESS';
export const DELETEUSER_FAILURE = 'USERS_DELETEUSERFAILURE';
